// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaQcHUTa2zf9jMPSYYDObB73dWncm3IjM',
    appId: '1:175537780570:web:80655525ca05404d402563',
    messagingSenderId: '175537780570',
    projectId: 'tp-guide-ipssi',
    authDomain: 'tp-guide-ipssi.firebaseapp.com',
    storageBucket: 'tp-guide-ipssi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ9vqS0NEOzNNt0D7PGjbsBDCthkgejdA',
    appId: '1:175537780570:android:8b257b1bb00f14dc402563',
    messagingSenderId: '175537780570',
    projectId: 'tp-guide-ipssi',
    storageBucket: 'tp-guide-ipssi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeozTCwzvWSEAMk_-ZcpNSVWBW58_7ztc',
    appId: '1:175537780570:ios:962934e331ecc164402563',
    messagingSenderId: '175537780570',
    projectId: 'tp-guide-ipssi',
    storageBucket: 'tp-guide-ipssi.appspot.com',
    iosBundleId: 'com.example.flutterClassTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeozTCwzvWSEAMk_-ZcpNSVWBW58_7ztc',
    appId: '1:175537780570:ios:962934e331ecc164402563',
    messagingSenderId: '175537780570',
    projectId: 'tp-guide-ipssi',
    storageBucket: 'tp-guide-ipssi.appspot.com',
    iosBundleId: 'com.example.flutterClassTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaQcHUTa2zf9jMPSYYDObB73dWncm3IjM',
    appId: '1:175537780570:web:f43e6aff33ab07d3402563',
    messagingSenderId: '175537780570',
    projectId: 'tp-guide-ipssi',
    authDomain: 'tp-guide-ipssi.firebaseapp.com',
    storageBucket: 'tp-guide-ipssi.appspot.com',
  );
}